export type ReleaseNotesLanguage = "ja" | "en";
export type BundledReleaseNotesHistoryEntry = {
    version: string;
    releaseNotes: string;
};

type ReleaseNotesEntry = {
    ja: string;
    en: string;
};

const RELEASE_NOTES: Record<string, ReleaseNotesEntry> = {
    "0.8.25": {
        ja: [
            "[修正] 右クリックコンテキストメニュー全体の表示アニメーションを無効化し、フォルダ・ライブラリアイテムとも表示後に少し上へずれる不自然な挙動をなくしました。",
            "[修正] コンテキストメニューの表示アニメーション後に位置を再計算するようにし、画面下端付近で下限余白が 0px やマイナスになる場合がある問題を修正しました。",
            "[修正] ライブラリ内アイテムのコンテキストメニューにもフォルダ右クリックと同じ 4px の下限余白を適用し、タグ・フォルダーピッカーの下限余白も同じ値で統一しました。",
            "[修正] インスペクターの「ブラウザで開く」をクリック完了待ちではなく押下時点で起動するようにし、外部ブラウザが開くまでの体感遅延を減らしました。",
            "[修正] ライブラリカードとリスト行のネイティブファイルドラッグで、OS 側のドラッグ開始 Promise が完了するまでドラッグ状態を維持するようにし、`[MediaCard] Starting native drag directly...` が出ても実際のドラッグが始まらないケースを減らしました。",
            "[変更] `startDrag` のデスクトップ API を非同期完了まで待てる Promise 返却に統一し、ドラッグ開始直後に UI 側が状態を片付けてしまう競合を防ぐようにしました。",
            "[修正] インスペクターのタグピッカーとフォルダーピッカーが画面下にはみ出す場合に、ライブラリ右クリックメニューと同じ下限余白を保って上方向へ収めるようにしました。",
            "[変更] ライブラリ切り替えメニューとライブラリ右クリックメニューが画面下端に近い場合でも、ウィンドウ下部に余白を残した位置へ自動調整するようにしました。",
        ].join("\n"),
        en: [
            "[Fix] Disabled open animations for right-click context menus so folder and library item menus no longer shift upward after appearing.",
            "[Fix] Context menus now recalculate their position after the open animation so bottom padding no longer collapses to 0px or negative values near the window edge.",
            "[Fix] Applied the same 4px bottom padding to the library item context menu and unified the Inspector tag/folder picker bottom padding with the folder context menu value.",
            "[Fix] The Inspector `Open in browser` action now fires on pointer press instead of waiting for click completion, reducing perceived delay before the external browser opens.",
            "[Fix] Native file drags from library cards and list rows now keep drag state alive until the OS drag-start promise settles, reducing cases where `[MediaCard] Starting native drag directly...` appears but no real drag begins.",
            "[Change] Unified the desktop `startDrag` API to return a Promise so callers can wait for drag startup instead of tearing down UI drag state immediately.",
            "[Fix] Kept the Inspector tag picker and folder picker inside the viewport by applying the same bottom padding behavior used by library context menus.",
            "[Change] Library switch menus and library context menus now keep a small gap from the bottom edge instead of pinning flush to the window.",
        ].join("\n"),
    },
    /* legacy 0.8.23 notes kept temporarily for cleanup context
    "0.8.23": {
        ja: [
            "[修正] Discord Rich Presence sidecar の update 判定が旧 `discordClient` 変数を見たままになっていたため、`pipe=1` 接続成功後でも `result:false` を返していた問題を修正しました。",
            "[修正] Discord Rich Presence sidecar 内の update / clear を直列化し、起動直後やプレイヤー切り替え時の重複リクエストで接続状態が競合しにくいようにしました。",
            "[修正] Discord Rich Presence sidecar の古い IPC ソケットから届く `READY` / `close` イベントが新しい接続試行へ混線しないようにし、`sidecar ready pipe=unknown` の後に update が false で落ち続ける問題を修正しました。",
            "[修正] 起動直後など Discord sidecar がまだ未接続の状態で `clear` が先に呼ばれた場合は no-op 成功として扱うようにし、`sidecar discord clear returned false` エラーが不要に出る問題を修正しました。",
            "[修正] Discord Rich Presence の sidecar は `discord-rpc` の固定 pipe 0 依存をやめ、実際に応答している Discord IPC pipe を探索して接続するようにし、Discord Canary / PTB 環境で表示されない問題を修正しました。",
            "[修正] Discord Rich Presence の sidecar が `result:false` を返した場合でも bridge 側で成功扱いしていたためエラーが見えなかった問題を修正し、更新・クリア失敗を正しくログへ出すようにしました。",
            "[変更] Discord Rich Presence の更新とクリアは、起動失敗が続いていた Rust `discord-sdk` 経路ではなく、実際に安定動作している sidecar IPC 経路を正規ルートとして使うように戻しました。",
            "[修正] Rust の Discord RPC は `Discord::new()` 直後に即更新せず `Ready` handshake 完了を待ってから activity を送るようにし、起動直後の `Browsing Library` 更新で初回接続が timeout しやすかった問題を修正しました。",
            "[変更] Discord Rich Presence の bridge 側では同一 payload の短時間重複送信だけを抑制しつつ、Rust 経路の待ち時間は初回 handshake を考慮して少し長めにしました。",
            "[修正] Discord Rich Presence の Rust 経路で更新要求が同時に詰まると 2 秒 timeout が連鎖していたため、Rust 側が処理中の間は即 sidecar フォールバックへ切り替えるようにして待ち行列由来の timeout を減らしました。",
            "[修正] Discord Rich Presence の Rust 経路が `channel is disconnected` や timeout に入った後も毎回再試行していたため、一定時間は即座に sidecar フォールバックへ渡すクールダウンを追加して、再起動後に `discord_update_activity timed out after 2000ms` が連発しにくいようにしました。",
            "[修正] 次の動画へ切り替えた直後に前の動画の `Paused` 状態が Discord リッチプレセンスへ残って新しい動画の `Watching` シークバーが出なくなることがあったため、現在の media と一致しない古い要素イベントを無視するようにしました。",
            "[変更] Discord リッチプレセンスの `Paused` 表示中は timestamp を送らないようにして、停止中にシークバーだけが進み続けにくい挙動へ調整しました。",
            "[修正] 右上の閉じるボタンでアプリ終了時に Discord 切断や sidecar kill の完了待ちで UI が止まらないよう、ウィンドウ close を先に通し、後片付けはバックグラウンドで実行するようにしました。",
            "[修正] プレイヤーの Discord 更新 effect が `currentTime` / `duration` 変化ごとに再生成されて更新要求が過剰発生していたため、イベント駆動の更新だけに戻して `Watching` への切り替えが不安定になる問題を修正しました。",
            "[修正] プレイヤーを閉じてライブラリ表示へ戻る直前に Discord リッチプレセンスを明示クリアするようにし、再生中だった `Watching` のシークバーが残ったまま進み続けることがある問題を修正しました。",
            "[変更] Discord リッチプレセンスの activity type を sidecar フォールバック時も `Listening` / `Watching` に合わせて送るようにし、`Playing` 表示へ戻ってしまうケースを減らしました。",
            "[修正] Discord リッチプレセンスの再生 timestamp 更新を `loadedmetadata` / `durationchange` / `ratechange` / `timeupdate` にも追従させ、シークバーが表示されない、または再生位置がずれやすい問題を改善しました。",
            "[修正] Discord リッチプレセンスは Rust 経由を再び優先しつつ、Rust 側の送信に失敗した場合だけ sidecar `discord-rpc` へフォールバックするようにしました。",
            "[修正] Tauri / Rust 側の Discord Activity payload を見直し、`instance` と button を扱えるようにして YouTubeDiscordPresence に近い送信形式へ寄せました。",
            "[修正] Tauri / Rust 側の Discord SDK へ渡す timestamp をミリ秒から Unix 秒へ正規化するようにし、シークバー用の再生時刻が正しく解釈されるようにしました。",
            "[修正] Rust 側の Discord 更新が一度失敗したときはクライアントを切断して再接続し、再送を 1 回試すようにして表示が消えやすいケースを減らしました。",
            "[修正] Discord リッチプレセンスの debug log に `instance` と button 数も残すようにし、Rust 経路の表示不具合を追いやすくしました。",
            "[修正] プレイヤーのオーバーレイ Canvas で毎フレーム resize 判定を繰り返していた処理を抑え、プレイヤー画面表示中に `Canvas resized ...` ログが大量発生して重くなる問題を軽減しました。",
            "[修正] アプリの `×` で閉じる処理が Discord 切断待ちで止まらないよう、終了時の Discord clear / disconnect にタイムアウトを設けました。",
        ].join("\n"),
        en: [
            "[Fix] Corrected the Discord Rich Presence sidecar update path to check the live `discordSocket` state instead of the removed `discordClient` variable, which was causing `result:false` even after a successful pipe connection.",
            "[Fix] Serialized sidecar Discord update / clear operations so duplicate startup and player-transition requests are less likely to race each other.",
            "[Fix] Isolated Discord Rich Presence sidecar IPC events per connection attempt so stale `READY` / `close` events from old sockets no longer corrupt a new connection and cause repeated `result:false` updates.",
            "[Fix] Discord clear requests are now treated as a successful no-op when the sidecar has not connected yet, preventing unnecessary `sidecar discord clear returned false` errors during startup.",
            "[Fix] The Discord Rich Presence sidecar no longer assumes Discord IPC pipe 0 and now probes the live Discord IPC pipes before connecting, restoring Rich Presence on Discord Canary / PTB setups where pipe 0 immediately closes.",
            "[Fix] The desktop bridge now treats sidecar `result:false` responses as actual Discord RPC failures instead of logging them as success, so update and clear failures are surfaced correctly.",
            "[Change] Discord Rich Presence update/clear now use the stable sidecar IPC path as the primary route instead of the Rust `discord-sdk` path that was repeatedly failing to start in this environment.",
            "[Fix] Rust Discord Rich Presence now waits for the Discord SDK `Ready` handshake before sending the first activity update, fixing startup-time timeouts on the initial `Browsing Library` presence.",
            "[Change] The bridge now only suppresses short-window duplicate Discord payloads, and the Rust-path timeout was extended slightly to account for the initial handshake.",
            "[Fix] Rust Discord Rich Presence updates now fail fast while another Rust update is already in flight, reducing timeout cascades from queued requests and letting the sidecar fallback handle bursty updates immediately.",
            "[Fix] Added a cooldown after Rust Discord RPC disconnect/timeout failures so updates fall back to the real sidecar path immediately instead of timing out on every request.",
            "[Fix] Discord Rich Presence now ignores stale media-element events during next/previous track switches so the previous item's paused state is less likely to override the new item's `Watching` activity.",
            "[Change] Paused Discord Rich Presence updates now omit timestamps so the progress bar does not keep advancing while playback is stopped.",
            "[Fix] Closing the app from the top-right close button no longer waits for Discord teardown or sidecar kill to finish before closing the window; cleanup now runs in the background.",
            "[Fix] The player's Discord update effect no longer recreates itself on every `currentTime` / `duration` change, reducing update floods and restoring stable transitions into `Watching` activity.",
            "[Fix] The app now clears Discord Rich Presence immediately before closing the player and returning to the library, preventing the previous `Watching` progress bar from continuing when the idle update is delayed or fails.",
            "[Change] Discord Rich Presence now preserves `Listening` / `Watching` activity types even when the update falls back to the sidecar path, reducing cases where Discord shows `Playing` instead.",
            "[Fix] Improved Discord Rich Presence timestamp syncing by also reacting to `loadedmetadata`, `durationchange`, `ratechange`, and throttled `timeupdate` events so the progress bar appears more reliably and stays aligned with playback.",
            "[Fix] Discord Rich Presence now prefers the Rust path again, only falling back to the sidecar `discord-rpc` path when the Rust update fails.",
            "[Fix] Aligned the Tauri / Rust Discord activity payload more closely with YouTubeDiscordPresence by supporting `instance` and buttons.",
            "[Fix] Normalized Rich Presence timestamps for the Tauri / Rust Discord SDK from milliseconds to Unix seconds so playback timing is interpreted correctly.",
            "[Fix] Rust-side Discord updates now disconnect, reconnect, and retry once after an update failure so Rich Presence is less likely to disappear.",
            "[Fix] Discord Rich Presence debug logging now includes `instance` and button count details to make Rust-path issues easier to diagnose.",
            "[Fix] Reduced excessive overlay canvas resize checks in the player so `Canvas resized ...` logs no longer flood while the player is open.",
            "[Fix] Added timeouts to Discord clear/disconnect during shutdown so the app close button does not get stuck waiting on Discord teardown.",
        ].join("\n"),
    },
    */
    "0.8.24": {
        ja: [
            "[修正] ライブラリ内のメディアを通常ドラッグしたとき、Discord や X などの外部アプリへネイティブファイルドラッグとして渡せるように修正しました。",
            "[変更] ライブラリ内のアプリ内ドラッグ&ドロップ操作は Shift を押しながら行う仕様に整理しました。",
            "[修正] 一覧表示で複数選択したメディアを外部アプリへドラッグした際、選択したファイル一式をまとめて渡すように修正しました。",
        ].join("\n"),
        en: [
            "[Fix] Library media can now be dragged normally into external apps such as Discord and X as native file drags.",
            "[Change] Internal drag-and-drop within the library is now consistently performed with Shift held.",
            "[Fix] List view now includes all selected files when dragging media out to external apps.",
        ].join("\n"),
    },
    "0.8.23": {
        ja: [
            "[修正] Discord Rich Presence の sidecar 接続を安定化し、`discord-rpc` の固定 pipe 0 依存をやめて、実際に応答している Discord IPC pipe へ接続するようにしました。Discord Canary / PTB 環境でも表示されやすくなります。",
            "[修正] Discord Rich Presence の sidecar で古い IPC ソケットの `READY` / `close` イベントが新しい接続試行へ混線しないようにし、接続済みに見えるのに更新が失敗する問題を修正しました。",
            "[修正] Discord Rich Presence の sidecar 更新処理が旧 `discordClient` 変数を見て `result:false` を返していた問題を修正し、接続成功後の activity 更新が正しく通るようにしました。",
            "[修正] Discord Rich Presence の update / clear を sidecar 内で直列化し、起動直後やプレイヤー切り替え時の重複リクエストで接続状態が競合しにくいようにしました。",
            "[修正] Discord Rich Presence の sidecar が `result:false` を返した場合でも bridge 側で成功扱いしていた問題を修正し、更新・クリア失敗を正しくログへ出すようにしました。",
            "[修正] 起動直後など Discord sidecar がまだ未接続の状態で `clear` が先に呼ばれた場合は no-op 成功として扱うようにし、不要な `sidecar discord clear returned false` エラーを抑えました。",
            "[変更] Discord Rich Presence の更新とクリアは、起動失敗が続いていた Rust `discord-sdk` 経路ではなく、安定していた sidecar IPC 経路を正規ルートとして使うように戻しました。",
            "[修正] Discord Rich Presence の activity type を sidecar 経路でも `Listening` / `Watching` に合わせて送るようにし、`Playing` 表示へ戻ってしまうケースを減らしました。",
            "[修正] Discord Rich Presence の再生位置同期を改善し、`loadedmetadata` / `durationchange` / `ratechange` / `timeupdate` に追従してシークバーが表示されない、またはずれやすい問題を改善しました。",
            "[変更] Discord Rich Presence の `Paused` 表示中は timestamp を送らないようにし、停止中にシークバーだけが進み続けにくい挙動へ調整しました。",
            "[修正] 次の動画へ切り替えた直後に前の動画の `Paused` 状態が新しい動画の `Watching` 表示を上書きしにくいよう、古い media 要素イベントを無視するようにしました。",
            "[修正] プレイヤーを閉じてライブラリ表示へ戻る直前に Discord Rich Presence を明示クリアするようにし、前の `Watching` シークバーが残り続けることがある問題を修正しました。",
            "[修正] 右上の閉じるボタンでアプリ終了時に Discord 切断や sidecar 停止待ちで UI が止まらないよう、ウィンドウ close を優先して後片付けをバックグラウンドで進めるようにしました。",
        ].join("\n"),
        en: [
            "[Fix] Stabilized Discord Rich Presence sidecar connections by probing the live Discord IPC pipes instead of assuming pipe 0, improving compatibility with Discord Canary / PTB environments.",
            "[Fix] Prevented stale `READY` / `close` events from old sidecar IPC sockets from corrupting new connection attempts and causing false Rich Presence update failures.",
            "[Fix] Corrected the sidecar update path to check the live `discordSocket` state instead of the removed `discordClient` variable, so activity updates succeed after a valid connection is established.",
            "[Fix] Serialized sidecar Discord update / clear operations so duplicate startup and player-transition requests are less likely to race each other.",
            "[Fix] The desktop bridge now treats sidecar `result:false` responses as actual Discord RPC failures instead of logging them as success, making update and clear failures visible in the logs.",
            "[Fix] Discord clear requests are now treated as a successful no-op when the sidecar has not connected yet, preventing unnecessary startup-time clear errors.",
            "[Change] Discord Rich Presence update and clear now use the stable sidecar IPC route as the primary path instead of the Rust `discord-sdk` path that was repeatedly failing in this environment.",
            "[Fix] Discord Rich Presence now preserves `Listening` / `Watching` activity types on the sidecar path, reducing cases where Discord falls back to `Playing`.",
            "[Fix] Improved Rich Presence timestamp syncing by reacting to `loadedmetadata`, `durationchange`, `ratechange`, and throttled `timeupdate` events so the progress bar stays aligned with playback.",
            "[Change] Paused Rich Presence updates now omit timestamps so the progress bar does not keep advancing while playback is stopped.",
            "[Fix] Rich Presence now ignores stale media-element events during next/previous track switches so an older paused item is less likely to override the new `Watching` activity.",
            "[Fix] The app now clears Discord Rich Presence immediately before closing the player and returning to the library, preventing the previous `Watching` progress bar from lingering.",
            "[Fix] Closing the app from the top-right close button no longer blocks on Discord teardown or sidecar shutdown before the window closes.",
        ].join("\n"),
    },
    "0.8.22": {
        ja: [
            "[修正] Discord リッチプレゼンスの呼び出し開始・Rust 経路成功・sidecar フォールバック成功・clear 実行を常に記録するようにし、`discord-presence.log` と bridge debug log から実行有無を追えるようにしました。",
            "[修正] Rust 側の Discord SDK 経路が利用できない環境でも表示が消えないよう、初期化や更新に失敗した場合は自動で旧 sidecar 経路へフォールバックし、失敗理由を DevTools と debug log に残すようにしました。",
            "[修正] Discord リッチプレゼンスの更新処理を Node 側の `discord-rpc` から Tauri / Rust 側の Discord SDK 実装へ切り替え、記事で触れられている `Watching` / `Listening` の Activity kind を反映できるようにしました。",
            "[修正] Discord リッチプレゼンスの再生状態判定を実際の media 要素の `paused` 状態に合わせ、動画再生中に `Paused` と表示されることがある問題を修正しました。",
            "[修正] Discord RPC / Social SDK の仕様に合わせ、先頭行の `Playing` は Discord 側の自動表示として残しつつ、Obscura 側の文脈は `details` / `state` で `Watching` / `Listening` と伝えるよう整理しました。",
            "[変更] Discord リッチプレゼンスの大きいアイコンをゲーム風アイコンではなくモニターアイコンへ変更しました。",
            "[修正] アプリ終了時に Discord リッチプレゼンスが残ることがある問題を修正しました。終了前に Discord の表示を明示的にクリアし、ウィンドウ close 時には sidecar も停止するようにしました。",
            "[変更] 更新完了モーダルでは更新履歴本文の上に `🎉 version x.x.x updated` の見出しを表示するようにし、更新通知と履歴本文を見た目で分けました。",
            "[修正] auto-import 完了時と起動直後に自動で走っていたライブラリ `images` の全スキャンを削除しました。不要な `refresh_library` が `scanRoot=...\\\\images` で停止し、Windows 既定アプリの誤起動やメタデータ読込タイムアウトを引き起こしていたためです。",
            "[修正] 起動直後の既定アプリ誤起動の切り分け用として、startup metadata・refresh_library・get_media_files・ffprobe・ffmpeg thumbnail に診断ログを追加しました。",
            "[修正] auto-import 中の既定アプリ誤起動を追跡するため、native drag・shell action・auto-import・sidecar import の詳細ログを追加しました。",
            "[修正] auto-import 中に Windows 既定アプリで動画が開く不具合を追跡するため、native drag・shell action・auto-import・sidecar import の詳細ログを追加しました。",
            "[修正] 起動直後の動画外部再生とメタデータ読込タイムアウトを切り分けるため、startup metadata・refresh_library・get_media_files・ffprobe・ffmpeg thumbnail の診断ログを追加しました。",
            "[修正] auto-import 完了時と起動直後の自動 `refresh_library` をやめ、ライブラリ `images` 全走査を自動実行しないようにしました。これにより scanRoot=`...\\images` 直後に停止して既定アプリ再生へ波及する経路を回避します。",
            "[修正] ライブラリ一覧で通常の左ドラッグだけでは Windows へのネイティブファイルドラッグを開始しないようにし、Alt+ドラッグ時のみ OS へファイルを渡すよう変更しました。これにより既定の動画アプリが勝手に連続起動する経路を遮断しました。",
            "[修正] 自動インポート監視にライブラリ本体、ライブラリ配下、またはライブラリを含む親フォルダを登録できないようにし、ライブラリ内動画を再帰的に拾って不安定化する設定ミスを防ぐようにしました。",
            "[修正] Windows の「エクスプローラーで表示」は `cmd /c start` ではなく `explorer.exe` を使うよう変更し、ファイル指定時は `/select,` で Explorer に限定して開くようにしました。",
            "[修正] 自動インポート実行中はネイティブファイルドラッグ自体を無効化し、完了前後も追加で一時抑止するようにして、一覧の再描画タイミングで Windows 既定アプリへ動画ファイルが渡って勝手に再生される経路を遮断しました。",
            "[修正] 自動インポート完了後のライブラリ更新は二重の `Refresh Library` をやめて `api.refreshLibrary()` と `reloadLibrary()` の 1 回ずつに整理し、完了までの不自然な待ち時間を短縮しました。",
            "[修正] 起動中はライブラリの初期化が終わるまでネイティブファイルドラッグを継続的に抑止し、さらにユーザー操作の活性がない状態では `startDrag` 自体を拒否するようにして、起動直後に動画が既定アプリで連続再生される経路を遮断しました。",
            "[修正] 起動中および自動インポート中は `openPath` / `showItemInFolder` / `openWith` の shell-open 自体も bridge で無効化し、バックグラウンド処理や誤発火した UI から既定アプリが起動しないようにしました。",
        ].join("\n"),
        en: [
            "[Fix] Added always-on Discord Rich Presence diagnostics so update attempts, Rust-path success, sidecar fallback success, and clear calls are recorded in both the bridge debug log and `discord-presence.log`.",
            "[Fix] Added a fallback from the Rust Discord SDK path back to the legacy sidecar path so Rich Presence does not disappear entirely when Rust-side initialization or updates fail, and those failures are now logged to DevTools and the debug log.",
            "[Fix] Moved Discord Rich Presence updates from the Node-side `discord-rpc` path to a Tauri / Rust Discord SDK implementation so Obscura can send `Watching` / `Listening` activity kinds directly.",
            "[Fix] Fixed Discord Rich Presence playback state detection to follow the actual media element `paused` state, preventing videos from being shown as `Paused` while playing.",
            "[Fix] Aligned Discord Rich Presence with the official RPC / Social SDK behavior: Discord keeps the automatic `Playing` label on the first line, while Obscura now expresses `Watching` / `Listening` through `details` and `state`.",
            "[Change] Changed the large Discord Rich Presence icon from the game-style icon to a monitor icon.",
            "[Fix] Fixed an issue where Discord Rich Presence could remain after the app exited. The app now clears Discord activity before shutdown and also stops the sidecar when the window closes.",
            "[Change] The post-update modal now shows a `🎉 version x.x.x updated` heading above the release notes body so the update notice is visually separated from the history text.",
            "[Fix] Removed the automatic full-library `images` rescan that used to run at startup and after auto-import completion. That `refresh_library` pass was unnecessary and could stall at `scanRoot=...\\\\images`, cascading into default-app launches and metadata load timeouts on Windows.",
            "[Fix] Added startup diagnostic logging around startup metadata, `refresh_library`, `get_media_files`, `ffprobe`, and FFmpeg thumbnail generation to isolate remaining early-launch issues.",
            "[Fix] Added detailed diagnostic logging around native drag, shell actions, auto-import, and sidecar import flow so unexpected Windows default-app launches can be traced from the log.",
            "[Fix] Added detailed diagnostic logging around native drag, shell actions, auto-import, and sidecar import flow so unexpected Windows default-app launches can be traced from the log.",
            "[Fix] Native Windows file drag no longer starts from a plain left-drag in the library view. It now requires Alt+drag, preventing unintended launches of the default video app.",
            "[Fix] Auto-import watch paths can no longer point to the library itself, inside the library, or to a parent folder that contains the library.",
            "[Fix] Show-in-Explorer on Windows now uses `explorer.exe` directly and reveals files with `/select,` instead of relying on `cmd /c start`.",
            "[Fix] Native file drag is now disabled during auto-import itself and additionally suppressed around completion so list refreshes cannot hand video files off to the Windows default app.",
            "[Fix] Post-auto-import library updates were reduced to one `api.refreshLibrary()` plus one `reloadLibrary()` pass, shortening the delay before imported items appear.",
            "[Fix] Native file drag is now continuously suppressed until startup initialization finishes, and `startDrag` is rejected when there is no active user gesture, preventing startup-time launches of the default video app.",
            "[Fix] Shell-open actions (`openPath`, `showItemInFolder`, and `openWith`) are now also disabled in the bridge during startup and auto-import so background work or accidental UI triggers cannot launch the default app.",
        ].join("\n"),
    },
    "0.8.21": {
        ja: [
            "[修正] 自動インポート Watcher はライブラリ初期化完了前には起動しないようにし、起動直後の監視スキャンがタグ・フォルダ取得を詰まらせる不具合を修正しました。",
            "[修正] 自動インポート監視先やその走査結果がライブラリ本体・`images` 配下を指していた場合は self-import 対象から除外し、ライブラリ内部ファイルを再走査して不安定化する経路を防ぎました。",
            "[修正] ライブラリ起動直後はタグ・フォルダ取得が完了するまで自動インポートを待機するようにし、初期化途中で取り込みだけ先行して完了しなくなる不具合を修正しました。",
            "[修正] タグ・タググループ・フォルダ取得にタイムアウトを追加し、内部取得が応答待ちで止まってもライブラリ再読込と自動インポート完了処理が戻らなくなる問題を修正しました。",
            "[修正] 起動時に動画本体や音声本体のパスが `thumbnail_path` として残っている項目はサムネイル対象から除外し、ライブラリ読込直後のサムネイル先読みで Windows の既定動画アプリが勝手に開かないようにしました。",
            "[修正] 自動インポート後に同じメディアを index と manualMedia へ二重保存していたため `getMediaFiles` が極端に遅くなる問題を改善し、既存ライブラリの重複データも自動で縮約するようにしました。",
            "[修正] サムネイルの安全URL生成に失敗した項目があっても読込キュー全体が停止しないようにし、先頭2列以降のサムネイルが表示されなくなる不具合を修正しました。",
            "[修正] サムネイル読込キューは画像の `onload` 完了待ちではなく安全なURL生成が終わった時点で次へ進むようにし、遅い項目や lazy load で後続のグリッド全体が止まらないようにしました。",
            "[修正] sidecar 側でも動画・音声ファイルを `thumbnail_path` として返さないように正規化し、`/api/thumbnails/*` から実動画を返して WebView や Windows 既定アプリを誤発火させる経路を遮断しました。",
            "[修正] UI の画像表示とサムネイル先読みは `toThumbnailUrl()` を経由するように統一し、誤って動画URLを `<img>` や `new Image()` に渡さないようにしました。",
            "[修正] Rust 側の WebView ナビゲーションガードで遮断した動画URLをアプリデータ配下の `webview-navigation.log` に記録するようにし、起動時の勝手な再生経路を追跡しやすくしました。",
            "[修正] Inspector の関連メディア表示で残っていた `toMediaUrl` 参照を `toThumbnailUrl` に統一し、自動インポート完了直後に `toMediaUrl is not defined` でクラッシュする不具合を修正しました。",
            "[修正] プレイヤー画面の Inspector 内に残っていたプレイリスト表示と関連メディアピッカーの `toMediaUrl` 参照も `toThumbnailUrl` に置き換え、再生中に `toMediaUrl is not defined` でクラッシュする不具合を修正しました。",
            "[修正] ローカルサムネイル用 blob URL の解放を遅延させ、一覧更新や自動インポート直後に `blob:... net::ERR_FILE_NOT_FOUND` が出やすい問題を緩和しました。",
            "[修正] Windows で WebView が `asset.localhost` / `file://` の動画・音声ファイルへ top-level navigation しようとした場合は Rust 側の WebView ナビゲーションガードで拒否するようにし、ライブラリ起動直後に既定メディアアプリへ脱出して連続再生される経路を遮断しました。",
            "[修正] Windows でライブラリ起動直後に先頭の動画が既定メディアアプリで連続して開かれる問題に対応し、ローカルサムネイルを WebView へ直接渡さず fetch→blob URL 経由で表示するよう変更しました。",
            "[修正] ライブラリカードとリスト行の通常ファイルドラッグを HTML5 の dragstart 依存から外し、明示的なマウス移動しきい値を超えた時だけネイティブドラッグを直接開始するよう変更しました。Shift を押した内部移動だけ HTML5 DnD を使います。",
            "[修正] 起動直後やライブラリ再描画直後に WebView の既定ドラッグがサムネイルやメディア要素から誤発火し、Windows 既定アプリで動画が連続起動する経路を修正しました。明示的に arm したネイティブドラッグだけを許可し、それ以外のサムネイル・プレビュー要素の既定 drag を停止します。",
            "[修正] 「既定のアプリで開く」「プログラムから開く」「エクスプローラーで表示」は、コンテキストメニュー項目で明示的に arm された直後だけ実行する one-shot intent を `App.tsx` 側にも追加し、予期しないハンドラ呼び出しでは Windows へファイルを渡さないようにしました。",
            "[修正] ライブラリカードとリスト行のネイティブファイルドラッグを移動量しきい値付きに変更し、一覧更新や僅かなポインタ移動だけで Windows 側へファイルが渡って既定メディアアプリが起動してしまう問題を修正しました。",
            "[修正] 自動インポート完了時のライブラリ反映を完了通知後の再読込まで含めて統一し、再起動しないと新規ファイルが表示されないことがある問題を修正しました。",
            "[修正] ライブラリ更新やウィンドウのフォーカス変化をまたいで古いコンテキストメニューが残り、完了通知付近で Windows 既定メディアアプリが連続起動してしまう問題を修正しました。",
            "[修正] 起動直後など稀なタイミングでコンテキストメニューを開いた入力がそのまま「エクスプローラーで表示」のクリックとして流れ、動画が Windows 既定アプリで連続再生される不具合を修正しました。",
            "[修正] Windows の「エクスプローラーで表示」は `explorer.exe` 固定ではなく Windows 既定のファイラーで親フォルダを開くようにし、動画ファイル自体が既定アプリで誤再生される経路を解消しました。",
            "[修正] インポート時の `dominant_color` 取得処理をメタデータ再取得時と揃え、メタデータ由来で埋まらない場合はサムネイルまたは元動画から自動抽出するようにしました。",
            "[修正] ゴミ箱の「完全に削除」で確認モーダルの削除を押した直後にモーダルが閉じるようにし、削除処理待ちで残り続ける不具合を修正しました。",
            "[修正] D&D で複数ファイルをインポートした際に、途中の 1 件で失敗すると残りのインポートまで停止してしまう不具合を修正しました。",
            "[修正] アプリ再起動後でも保存済みアップデートインストーラーを見つけて起動できるようにしました。",
            "[修正] 自動インポート直後に一覧へ反映されず、再読み込みで同じファイルを再度取り込んでしまう不具合を修正しました。",
            "[修正] 自動インポートの重複判定が監視先ごとの対象ライブラリではなく現在のアクティブライブラリ基準になっていた問題を修正し、ライブラリ切り替えや再起動後の再取り込みを起こしにくくしました。",
            "[修正] 自動インポート監視フォルダに既にあるファイルと後から追加されたファイルのどちらでもインポートを開始し、完了後にライブラリを再読み込みするようにしました。",
            "[修正] 自動インポート完了イベントの重複処理と起動時スキャンの二重実行を見直し、同じファイルの再取り込みや一覧反映漏れを起こしにくくしました。",
            "[修正] `metadata.json` を生成できなかったファイルはインポート完了扱いにせずロールバックするようにし、不完全な登録を防ぐようにしました。",
            "[修正] `metadata.json` 書き込みをリトライ付きにし、自動インポートは実際に完了した件数だけ成功扱いに変更しました。`metadata.json` がないファイルの削除も同じ削除処理で行えるようにしました。",
            "[修正] インポート時の `metadata.json` 生成で `XAttrMetadata` を読み取り、拡張属性にあるメタデータも引き継げるようにしました。",
            "[修正] `XAttrMetadata` の読取失敗が `metadata.json` 作成失敗へ波及しないようにし、`metadata.json` 書き込みも単純なリトライ方式で安定化しました。",
            "[修正] `metadata.json` 作成失敗時の sidecar ファイルログとブリッジ側エラーログを追加し、失敗要因を追跡できるようにしました。",
            "[修正] sidecar のデバッグログを複数候補の `.sidecar-data/debug-fileops.log` へ出力するようにし、`metadata.json` が 0 件だった場合は成功通知を出さず失敗扱いに変更しました。",
            "[修正] インポート時の `metadata.json` 書き込みは git の過去版に近い単純な `writeFileSync` ベースへ戻し、書き込み後に実ファイルの存在も確認するようにしました。",
            "[修正] Windows で `showItemInFolder` が実ファイルを既定アプリで開かないようにし、`file_open_path` / `file_show_item_in_folder` の呼び出しログを追加しました。",
            "[修正] `openPath` / `showItemInFolder` / `openWith` の許可を action と対象パスに束縛し、別のバックグラウンド処理が直前の操作権限を使い回せないようにしました。",
            "[修正] shell-open の grant / consume / 実行結果とフロント側の呼び出しスタックを `.sidecar-data/debug-fileops.log` と DevTools に残すようにし、起動時の外部動画再生ループの原因を追跡しやすくしました。",
            "[修正] 自動インポート完了時のライブラリ更新を `api.refreshLibrary()` と `reloadLibrary()` の単一路線に整理し、重複した Refresh と手動リロード時の停止を起こしにくくしました。",
            "[修正] 自動インポート完了後に sidecar 側とフロント側の両方で `Refresh Library` を必ず実行するようにし、取り込み直後の一覧更新が抜けないようにしました。",
            "[修正] インポート時に `dominant_color` を自動抽出するようにし、元ファイル削除失敗時はリトライと警告ログを出すようにしました。",
            "[修正] `import_media` を 0.8.18 に近い処理へ戻し、最近追加した厳格な `metadata.json` 失敗判定で正常なインポートまで 0 件扱いになる不具合を修正しました。",
            "[修正] インポート時の `dominant_color` 復元で参照していた `stringOrEmpty` の未定義エラーを修正しました。",
            "[修正] 自動インポートの起動時スキャンを bridge 側へ一本化し、同時実行を直列化して二重取り込みや `Refresh Library` 抜けを起こしにくくしました。外部ファイル起動は 1 回の明示操作につき 1 回だけ許可するようにしました。",
            "[修正] 外部ファイル起動の許可をグローバル入力検知ではなく明示的な open 操作時だけに変更し、起動時に動画が既定ソフトで勝手に開く不具合を抑えました。自動インポート完了時の `Refresh Library` はライブラリ復元後に実行するようにしました。",
            "[修正] open 系 API は自動インポート中の一時ブロックに頼らず、明示操作で指定した action と対象パスが一致した時だけ sidecar が受け付けるようにしました。完了後は `refreshLibrary()` に加えて `reloadLibrary()` も実行します。",
            "[修正] プレーヤーの自動再生を明示的な再生要求トークン付きに変更し、起動直後に関係のない動画が勝手に再生される不具合を抑えました。",
            "[修正] 起動直後や明示的な再生操作なしではプレーヤーが再生を始めないようにし、プレーヤーを閉じた後は再生開始トークンをリセットするようにしました。",
            "[修正] 自動インポートで対象ライブラリに同じ動画が既に存在していても事前スキップせず一度インポートし、その後に重複確認ダイアログで処理できるようにしました。",
            "[修正] shell-open をフロントエンド session 単位で許可するようにし、リロード前の古い非同期要求が遅れて到着しても Windows 既定アプリで動画を開けないようにしました。",
            "[修正] ゴミ箱表示中に Delete キーで完全削除する時の確認手順を、インスペクタの「完全に削除」と同じ挙動に揃えました。",
            "[修正] ゴミ箱の「完全に削除」は Delete キーとインスペクタのどちらからでもアプリ内の確認モーダルを使うように統一しました。",
            "[修正] HMR リロード時は plugin system のグローバル API を dispose で破棄するようにし、不要な二重初期化警告を出しにくくしました。",
            "[修正] エクスプローラーで表示時の shell intent はフロント側で事前消費せず、sidecar 側の token/session 判定だけで処理するようにして誤ブロックを減らしました。",
            "[修正] フロントエンドのリロード開始時に shell-open session を sidecar へ明示的に破棄するようにし、古い画面由来の遅延要求で Windows 既定アプリが連続起動しないようにしました。",
            "[修正] Windows の「エクスプローラーで表示」を `Start-Process explorer.exe` ベースに切り替え、ファイルは `/select,` で選択し、起動経路のログを追加しました。",
        ].join("\n"),
        en: [
            "[Fix] Auto-import watchers now stay paused until library startup initialization finishes, preventing early watch scans from blocking tag and folder loading.",
            "[Fix] Auto-import now excludes watch paths and scan results that point into the library itself, including its `images` subtree, preventing self-import loops against internal library files.",
            "[Fix] Auto-import now waits for startup tag and folder loading before it begins, preventing imports from starting against a half-initialized library and never completing.",
            "[Fix] Added timeouts to tag, tag-group, and folder loading so library reloads and auto-import completion can recover even if metadata fetches stop responding.",
            "[Fix] Startup now drops `thumbnail_path` values that still point at the original video or audio file, preventing thumbnail prefetch from handing those files to the Windows default media app.",
            "[Fix] Thumbnail load queue entries now release correctly even when safe local URL generation fails, preventing later grid and list thumbnails from stalling after the first two columns.",
            "[Fix] Thumbnail queue sequencing now advances as soon as a safe URL is prepared instead of waiting for image `onload`, so slow or deferred images cannot stall the rest of the grid.",
            "[Fix] The sidecar now sanitizes `thumbnail_path` values and refuses to serve video or audio files from `/api/thumbnails/*`, closing a path that could still hand real media files to WebView or the Windows default media app.",
            "[Fix] Image rendering and thumbnail prefetch now go through `toThumbnailUrl()` so video URLs cannot accidentally reach `<img>` tags or `new Image()` thumbnail warmups.",
            "[Fix] The Rust-side WebView navigation guard now writes blocked media URLs to `webview-navigation.log` in app data so any remaining startup escape path can be traced precisely.",
            "[Fix] Unified the Inspector relations panel on `toThumbnailUrl()` so auto-import completion no longer crashes with `toMediaUrl is not defined`.",
            "[Fix] Delayed revocation of local thumbnail blob URLs to reduce `blob:... net::ERR_FILE_NOT_FOUND` during list refreshes and post-import updates.",
            "[Fix] Added a Rust-side WebView navigation guard that rejects top-level navigation to local audio/video asset URLs on Windows, preventing the library from escaping into the default media app during startup.",
            "[Fix] Added an App-level one-shot intent gate for `Open Default`, `Open With`, and `Show in Explorer`, so even if those handlers are invoked unexpectedly they will not hand files to Windows unless the matching context-menu item was explicitly armed first.",
            "[Fix] Added a movement threshold before native file drag starts from library cards and list rows so refresh-time reflow or tiny pointer movement can no longer hand media files to Windows and launch the default media app.",
            "[Fix] Auto-import completion now performs the final library refresh and reload after the completion handoff so newly imported files appear without requiring an app restart.",
            "[Fix] Closed stale media context menus across library updates and window focus changes so completion-time UI churn can no longer cascade into repeated launches of the Windows default media app.",
            "[Fix] Fixed a rare issue where the same input that opened the context menu could leak into the `Show in Explorer` item during startup and repeatedly launch videos in the Windows default app.",
            "[Fix] Windows `showItemInFolder` now opens the parent folder with the system's default file manager instead of forcing `explorer.exe`, eliminating the path that could misfire and launch video files in the default media app.",
            "[Fix] Import-time `dominant_color` extraction now matches metadata refresh and falls back to extracting from the thumbnail or media file when metadata does not provide a value.",
            "[Fix] The trash permanent-delete confirmation modal now closes immediately after confirmation instead of staying open until deletion finishes.",
            "[Fix] Fixed an issue where drag-and-drop multi-file imports could stop the remaining files after a single item failed mid-import.",
            "[Fix] Saved update installers can now be found and launched after the app has restarted.",
            "[Fix] Fixed an issue where auto-imported files were not shown immediately and could be imported again on reload.",
            "[Fix] Fixed auto-import duplicate detection so it checks the watch target library instead of the currently active library.",
            "[Fix] Auto-import now starts for both existing and newly added files in watched folders, and refreshes the library after completion.",
            "[Fix] Reduced duplicate auto-import completion handling and startup re-scans that could re-import the same files or delay library visibility.",
            "[Fix] Imports now roll back when `metadata.json` cannot be written, preventing incomplete library entries.",
            "[Fix] Added retry-backed `metadata.json` writes, only treat successfully completed auto-imports as imported, and use the same deletion flow for files even when `metadata.json` is missing.",
            "[Fix] `metadata.json` generation during import now reads `XAttrMetadata` as well, so metadata stored in extended attributes is carried over.",
            "[Fix] Failures while reading `XAttrMetadata` no longer cascade into `metadata.json` creation failures, and metadata writes now use a simpler retry path.",
            "[Fix] Added sidecar file logging and bridge-side error logging for `metadata.json` creation failures so the root cause can be traced.",
            "[Fix] Sidecar debug logs are now written to multiple `.sidecar-data/debug-fileops.log` candidates, and imports no longer show success when zero items completed metadata creation.",
            "[Fix] Restored import-time `metadata.json` writing closer to the previous `writeFileSync` behavior and now verify the file exists immediately after writing.",
            "[Fix] On Windows, `showItemInFolder` no longer opens media files in the default app, and calls to `file_open_path` / `file_show_item_in_folder` are now logged.",
            "[Fix] `openPath` / `showItemInFolder` / `openWith` are now authorized per action and target path, so background work cannot reuse a previous explicit open permission for a different file.",
            "[Fix] Added shell-open trace logging for grant / consume / execution plus the frontend call stack in both `.sidecar-data/debug-fileops.log` and DevTools, making startup external-video loops easier to trace.",
            "[Fix] Simplified post-auto-import library updates to a single `api.refreshLibrary()` plus `reloadLibrary()` path, reducing duplicate refreshes and hangs when the user reloads right after auto-import.",
            "[Fix] Auto-import now always runs both the sidecar and frontend `Refresh Library` steps after completion so newly imported items are reflected immediately.",
            "[Fix] Import now extracts `dominant_color` automatically and retries source cleanup with warning logs on failure.",
            "[Fix] Restored `import_media` closer to the 0.8.18 flow so the recent strict `metadata.json` failure handling no longer converts otherwise valid imports into zero-result failures.",
            "[Fix] Fixed the missing `stringOrEmpty` helper referenced while restoring `dominant_color` during import.",
            "[Fix] Unified startup auto-import scanning on the bridge side, serialized auto-import runs to avoid duplicate imports and missed refreshes, and made shell-open intent single-use so unexpected external video launches do not cascade.",
            "[Fix] Restricted shell-open permission to explicit open actions instead of global input tracking, preventing videos from opening on startup, and now run `Refresh Library` after restoring the active library following auto-import.",
            "[Fix] Shell-open requests no longer rely on a temporary auto-import block; the sidecar now only accepts them when the explicit user action matches the requested action and target path, and auto-import still runs `reloadLibrary()` after `refreshLibrary()`.",
            "[Fix] Switched player auto-start to require an explicit playback intent token so unrelated videos do not start playing right after startup.",
            "[Fix] Prevented playback from starting at startup without an explicit play request and reset the playback-start token when the player closes.",
            "[Fix] Auto-import no longer skips files just because the target library already contains matching media, and now imports them first so the duplicate confirmation flow can resolve the conflict afterward.",
            "[Fix] Scoped shell-open authorization to the current frontend session so delayed requests from a pre-reload UI can no longer open videos in the Windows default app.",
            "[Fix] Matched the confirmation flow for permanent deletion from the trash Delete key shortcut with the Inspector's Delete Permanently action.",
            "[Fix] Unified permanent deletion from the trash so both the Delete key shortcut and the Inspector use the in-app confirmation modal.",
            "[Fix] Dispose the plugin system global API during HMR reloads so unnecessary double-initialization warnings are less likely to appear.",
            "[Fix] Stopped consuming shell intents on the frontend before Explorer actions so `showItemInFolder` now relies on the sidecar's token/session check without false local blocks.",
            "[Fix] Explicitly unregister the frontend shell-open session when the UI reloads so delayed requests from the old screen can no longer cascade into repeated Windows default-app launches.",
            "[Fix] Switched Windows `showItemInFolder` to `Start-Process explorer.exe`, select files with `/select,`, and log the exact launch path so Explorer launch failures are easier to trace.",
        ].join("\n"),
    },
    "0.8.19": {
        ja: [
            "[修正] tauri:dev で保存したフィルタープリセットをビルド版でも読み込めるようにし、プリセット保存先を共通設定へ統一しました。",
            "[修正] インポート時に `dominant_color` が空白で保存される不具合を修正しました。",
            "[修正] メタデータ更新時に既存の `dominant_color` が空白で上書きされる不具合を修正しました。",
            "[新規] プラグイン向けにサイドバー項目・サイドバーセクション・ヘッダーボタン・インスペクター拡張セクションの正式 API を追加しました。",
            "[新規] プラグイン向けにインポート前後フックと media・tags・folders・libraries・client config へアクセスできる API を追加しました。",
            "[新規] 新しい拡張 API の動作確認用として Extensibility Demo プラグインを追加しました。",
            "[新規] プラグインがメイン画面として独自ビューを開ける main view API を追加しました。",
            "[修正] sidecar 応答待ちでアクティブライブラリ解決が止まると起動時のデータ読み込みが 0% のまま進まなくなる不具合を修正しました。",
            "[変更] 起動時にアクティブライブラリ取得や設定読み込みが一定時間でタイムアウトした場合は保存済み設定から復元して起動を継続するように変更しました。",
            "[変更] 起動時の読み込みが長時間進まない場合はデータ読み込みオーバーレイを自動解除してアプリ操作を継続できるフェイルセーフを追加しました。",
            "[変更] ビルド版でもプラグイン一覧を安定して見つけられるように、同梱プラグインをランタイム用ディレクトリへ同期するよう改善しました。",
            "[変更] 起動直後のフリーズを避けるため、プラグインスクリプトの自動実行をアプリ起動時には行わない構成へ見直しました。",
            "[変更] 起動時に自動読み込みされるプラグインも、設定画面の拡張機能タブにあるオンオフで制御されるようにしました。",
            "[変更] 起動時に有効なプラグインをすべて最初から読み込むように変更しました。",
            "[修正] サイドバー上のプラグイン項目だけがブラウザ既定の button 見た目になっていたため、通常のサイドバー項目と同じ描画へ揃えて文字サイズや余白や色がずれる不具合を修正しました。",
            "[修正] プラグインのメイン画面を開いている間も標準サイドバー項目がアクティブ表示のまま残る不具合を修正しました。",
            "[変更] 同梱プラグインのバージョンが更新された場合はランタイム用プラグインへ同期するように変更しました。",
        ].join("\n"),
        en: [
            "[Fix] Filter presets saved in tauri:dev now persist through the shared client config so build releases can load them as well.",
            "[Fix] Fixed an issue where `dominant_color` could be saved as blank during import.",
            "[Fix] Fixed an issue where metadata refresh could overwrite an existing `dominant_color` with a blank value.",
            "[New] Added first-class plugin APIs for sidebar items, sidebar sections, header buttons, and inspector extension sections.",
            "[New] Added plugin import hooks plus API access for media, tags, folders, libraries, and client config.",
            "[New] Added an Extensibility Demo plugin that exercises the new extension APIs.",
            "[New] Added a main view API so plugins can open their own full-page screens inside the app.",
            "[Fix] Fixed an issue where startup could remain stuck at 0% if active library resolution waited indefinitely for the sidecar.",
            "[Change] Changed startup to fall back to the saved client config when active library lookup or config loading times out.",
            "[Change] Added a fail-safe that automatically dismisses the startup loading overlay if startup does not progress for an extended period.",
            "[Change] Improved plugin discovery in packaged builds by syncing bundled plugins into the runtime plugin directory.",
            "[Change] Stopped auto-running plugin scripts during app startup to avoid freezes shortly after launch.",
            "[Change] Startup-loaded plugins are now controlled by the enable toggles in the Extensions settings tab.",
            "[Change] Startup now loads all enabled plugins from the beginning.",
            "[Fix] Changed sidebar plugin items to render with the same base styling as native sidebar items, fixing mismatched font size, spacing, and colors.",
            "[Fix] Fixed an issue where native sidebar tabs could remain highlighted while a plugin main view was open.",
            "[Change] Bundled plugins are now synced into the runtime plugin directory when their bundled version changes.",
        ].join("\n"),
    },
    "0.8.18": {
        ja: [
            "[修正] WASAPI モードで音量ボタンのミュート切り替えが正しく反映されない不具合を修正しました。",
            "[変更] インスペクターのURL入力フォントを游ゴシック系に見直しました。",
            "[修正] Discord の表示がライブラリ画面へ戻る際に一瞬リセットされてしまう不具合を改善しました。",
            "[修正] ライブラリ画面での Discord 表示が Paused のまま残ることがある不具合を改善しました。",
            "[修正] Discord リッチプレゼンスの接続が不安定になることがある不具合を改善しました。",
            "[修正] 既存ファイルの追加日が起動後に本日扱いになることがある不具合を修正しました。",
            "[修正] 再起動直後に大規模ライブラリの読み込みが 30% 付近で止まりやすい問題を改善しました。",
            "[修正] 起動後のライブラリ復元を改善しました。",
            "[修正] 一部ライブラリで重い走査経路に入り読み込みに失敗しやすい不具合を改善しました。",
            "[修正] Tauri 開発環境で再起動後に 5% 付近で止まりやすい不具合を改善しました。",
            "[変更] 未完成の Android 関連項目は GitHub の公開リリース対象外であることを明確にしました。",
            "[変更] Android のローカルビルド成果物と同梱 JDK ファイル向けの ignore ルールを更新しました。",
            "[新規] ローカル用の tasks メモと AGENTS 指示ファイルを ignore 対象に追加しました。",
            "[新規] 設定画面のアプリ更新確認ボタンの横にリリースノート表示ボタンを追加しました。",
            "[変更] 更新後UIを再利用して、更新履歴をいつでも確認できるようにしました。",
            "[新規] D&D インポートを移動扱いにできる設定を追加しました。",
            "[修正] D&D で追加したファイルの追加日ソートを修正しました。",
            "[変更] サムネイルの読み込みをより段階的に行うよう改善しました。",
            "[変更] タグ管理UIと件数表示を調整しました。",
            "[新規] サブフォルダー表示で子孫フォルダーまで含められるようにしました。",
            "[修正] アップデーターのインストーラー起動動作を改善しました。",
            "[変更] タブごと・フォルダーごとにスクロール位置を保持するようにしました。",
        ].join("\n"),
        en: [
            "[Fix] Fixed an issue where the mute button volume toggle did not apply in WASAPI mode.",
            "[Change] Updated the inspector URL input to use the Yu Gothic font stack.",
            "[Fix] Improved an issue where Discord activity could reset briefly when returning to the library screen.",
            "[Fix] Improved an issue where Discord could remain on Paused while browsing the library.",
            "[Fix] Improved a Discord Rich Presence issue that could leave the RPC connection in an unstable state.",
            "[Fix] Fixed an issue where some existing files could occasionally show today as their added date after startup.",
            "[Fix] Improved a startup issue where very large libraries could appear to stall around 30% after a device restart.",
            "[Fix] Improved library restoration after launch.",
            "[Fix] Reduced a heavy library scan path that could make some libraries fail to load.",
            "[Fix] Prevented Tauri dev startup from stalling at 5% after a device restart.",
            "[Change] Clarified that unfinished Android-related items are not part of the public GitHub release scope.",
            "[Change] Updated ignore rules for Android local build artifacts and bundled JDK files.",
            "[New] Added local task notes and AGENTS instructions to the ignore list.",
            "[New] Added a subtle release notes button next to the application update check button in Settings.",
            "[Change] Reused the post-update UI so bundled update history can also be viewed on demand.",
            "[New] Added an option to treat drag-and-drop imports as move operations.",
            "[Fix] Fixed import-date sorting for files added via drag and drop.",
            "[Change] Improved thumbnail loading to happen progressively.",
            "[Change] Refined the tag manager UI and count display.",
            "[New] Subfolder content display can now include nested descendants.",
            "[Fix] Improved installer launch behavior in the updater.",
            "[Change] Scroll position is now preserved per tab and per folder.",
        ].join("\n"),
    },
};

const normalizeVersion = (input: string): string => {
    const raw = String(input || "").trim();
    const match = raw.match(/(\d+\.\d+\.\d+)/);
    return match ? match[1] : raw;
};

const compareVersionsDesc = (left: string, right: string): number => {
    const leftParts = normalizeVersion(left)
        .split(".")
        .map((part) => Number(part) || 0);
    const rightParts = normalizeVersion(right)
        .split(".")
        .map((part) => Number(part) || 0);

    for (let i = 0; i < 3; i += 1) {
        const delta = (rightParts[i] || 0) - (leftParts[i] || 0);
        if (delta !== 0) return delta;
    }

    return 0;
};

export const getBundledReleaseNotes = (
    version: string,
    language: ReleaseNotesLanguage,
): string => {
    const normalizedVersion = normalizeVersion(version);
    const entry = RELEASE_NOTES[normalizedVersion];
    if (!entry) return "";
    return language === "en" ? entry.en : entry.ja;
};

export const getBundledReleaseNotesHistory = (
    language: ReleaseNotesLanguage,
): BundledReleaseNotesHistoryEntry[] => {
    return Object.keys(RELEASE_NOTES)
        .sort(compareVersionsDesc)
        .map((version) => ({
            version,
            releaseNotes: getBundledReleaseNotes(version, language).trim(),
        }))
        .filter((entry) => entry.releaseNotes.length > 0);
};
